### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.exemple.myapplication/files/dynamic_so/libtest.so" has unexpected e_version: 65725

### ISSUE THREAD

**Issue by lgh001** [TestPlanB/SillyBoy#6]
在用demo尝试的时候，发生了这个错误

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.exemple.myapplication/files/dynamic_so/libtest.so" has unexpected e_version: 65725
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.exemple.myapplication.TestSo.<clinit>(TestSo.kt:41)
        at com.exemple.myapplication.MainActivity.onCreate$lambda-3(MainActivity.kt:62)
        at com.exemple.myapplication.MainActivity.$r8$lambda$04hyejgvbGZzKFahH40V5n53yRg(Unknown Source:0)
        at com.exemple.myapplication.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)

打印classLoader的时候，确认自定义的solib已经插入nativeLibraryDirectories

dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.lgh.myapplication-8GvN7C-0ytdB_y8C5cgMpw==/base.apk"],nativeLibraryDirectories=[/data/user/0/com.exemple.myapplication/files/dynamic_so, /data/app/com.exemple.myapplication-8GvN7C-0ytdB_y8C5cgMpw==/lib/arm64, /data/app/com.exemple.myapplication-8GvN7C-0ytdB_y8C5cgMpw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]]

同时要加载的so库也已经放到/data/user/0/com.exemple.myapplication/files/dynamic_so目录下

求解

**Comment by TestPlanB** [comment]
请问这个so是正常的so嘛，因为elf文件头都失败了。可以运行app一下编译生成一个so，放到自己的目录哦

**Comment by SashaCube** [comment]
Have the same issue but with other .so lib, any updates on this?
