### ISSUE TITLE
 has invalid shdr offset/size

### ISSUE THREAD

**Issue by wentianyang** [TestPlanB/SillyBoy#8]
"java.lang.UnsatisfiedLinkError: dlopen failed: ""/data/data/com.example.demo/files/dynamic_so/libVECoreFFmpeg.so"" has invalid shdr offset/size: 20189888/1344
 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
 	at java.lang.System.loadLibrary(System.java:1657)
 	at YHlnQn.tDgmK.XBLtLhuy(DynamicSo.java:195) 
	at YHlnQn.tDgmK.XBLtLhuy(DynamicSo.java:105) 
	at YHlnQn.tDgmK.XBLtLhuy(DynamicSo.java:105)
 	at com.pika.sillyboy.DynamicSoLauncher.loadSoDynamically(DynamicSoLauncher.kt:3)

从远程服务器上下载 so，手动加载后会出现以上问题

**Comment by TestPlanB** [comment]
这个需要自己排查一下so文件的完整性，看样子是这个so本身的问题
